#!/bin/bash

set -e

fail=0

if [[ "$1" == "--fail" ]]; then
    fail=1
fi

case $fail in
    0)
    api_secret=$(docker-compose run -T conjur-cli variable value helloworld-secret)
    echo "Connecting with API secret: $api_secret"
    curl -H "Authorization:Token token=\"$api_secret\"" localhost:8080
    ;;
    1)
    # Send an invalid password to the helloworld app
    curl -H "Authorization:Token token=\"invalid token\"" localhost:8080
    ;;
esac
