version: "3"
services:
  
  helloworld:
    image: conjur-rotation-demo-helloworld
    build: ./helloworld
    volumes:
      - ./helloworld/helloworld.rb:/app/helloworld.rb
    ports:
      - "8080:4567"
    environment: 
      RACK_ENV: DEMO
      CONJUR_AUTHN_LOGIN: host/helloworld
      CONJUR_AUTHN_API_KEY: 
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: demo

    depends_on: [ conjur ]

  consumer:
    image: conjur-rotation-demo-consumer
    build: ./consumer
    volumes:
      - ./consumer/consumer:/app/consumer
    environment: 
      CONJUR_AUTHN_LOGIN: host/consumer
      CONJUR_AUTHN_API_KEY: 
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: demo

    depends_on: [ conjur, helloworld ]

  conjur:
    image: cyberark/conjur
    command: server -a demo
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY:
    depends_on: [ database ]
    
  database:
    image: postgres:9.3

  conjur-cli:
    image: cyberark/conjur-cli:5
    depends_on: [ conjur ]
    volumes:
      - ./cli:/root
