#!/bin/bash

set -eu

# Initialize Conjur with the demo account
cat << CONJURRC > ./cli/.conjurrc
appliance_url: http://conjur
account: demo
CONJURRC

# Fetch admin API key
api_key=$(docker-compose exec conjur conjurctl role \
            retrieve-key demo:user:admin | tr -d "\r\n")

# Login as the Conjur Admin and load the demo policy
docker-compose run --rm conjur-cli authn login -u admin -p $api_key
docker-compose run --rm -T conjur-cli policy load root /root/policy.yaml
