#!/bin/bash

consumer_id="consumer"

export CONJUR_AUTHN_API_KEY=$(\
    docker-compose run -T client host rotate_api_key \
    --host "$consumer_id" \
    | tr -d "\r\n")

docker-compose run consumer $@
