#!/bin/bash

set -eu

docker-compose run --rm -T --entrypoint "/bin/bash" client bash -c \
    'conjur client plugin install policy \
    && conjur policy load --as-role group:security_admin /root/policy.yaml'
