#!/bin/bash

set -e

# Pull required container images from Docker Hub
echo 'Pulling Docker images...'
docker-compose pull --quiet conjur

# Remove containers and files created in earlier runs (if any)
echo 'Bringing up fresh containers...'
docker-compose down
rm cli/.conjurrc

# Start containers & wait for Conjur to be responsive
docker-compose up -d
echo 'Waiting for Conjur to be ready...'
docker-compose exec conjur /opt/conjur/evoke/bin/wait_for_conjur

# Prepare the client to connect to the Conjur server
# Initialize the Conjur client
echo 'Connecting the client to the Conjur server...'
docker-compose run --rm client init -h https://conjur -a cucumber
docker-compose run --rm client authn login -u admin -p secret
